name: "Custom GitHub Action with SonarScanner, kubectl, and Terraform"
description: "Runs SonarScanner, Terraform, and kubectl commands in a containerized GitHub Action."

runs:
  using: "docker"
  image: "Dockerfile"  # O Dockerfile que define o ambiente
  args:
    - ${{ inputs.sonar-command }}
    - ${{ inputs.kubectl-command }}
    - ${{ inputs.terraform-command }}

inputs:
  kubectl-command:
    description: "Custom kubectl command to run"
    required: false
    default: "get pods" 

  sonar-command:
    description: "Custom SonarScanner command to run"
    required: false
    default: "sonar-scanner -Dsonar.projectKey=default" 

  terraform-command:
    description: "Custom Terraform command to run"
    required: false
    default: "terraform plan"  # Valor padrão
