name: "Custom GitHub Action with SonarScanner, kubectl, and Terraform"
description: "Runs SonarScanner, Terraform, and kubectl commands in a containerized GitHub Action."

runs:
  using: "docker"
  image: "Dockerfile" 
  args:
    - ${{ inputs.sonar-command }}
    - ${{ inputs.kubectl-command }}
    - ${{ inputs.terraform-command }}
