# .github/workflows/main.yml
name: "devops-tools-acions - teste"

on:
  push:
    branches:
      - main

jobs:
  run-custom-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run custom action
        uses: ./
        
      - name: Teste kubectl
        run: kubectl version
      - name: Teste Terraform
        run: terraform --version
      - name: Teste SonarScanner
        run: sonar-scanner --version
